version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip3 install pytest
  build:
    on-failure: ABORT
    commands:
      - echo "Running lambda tests..."
      - python -m pytest tests/
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name lambda_casino_birthdate_control --zip-file fileb://deployment_package.zip
      - echo "The lambda function aws updated successfully!"